FROM python:3.7

# Create app directory
WORKDIR /app

# Install app dependencies
COPY ./requirements.txt ./

RUN pip install -r requirements.txt

# Bundle app source
COPY src /app/src

EXPOSE 5008
CMD [ "python", "src/app.py" ]